
#import <Foundation/Foundation.h>

//#define PLATFORM_MAC_OS_X

//	Global enum
typedef enum OBUnitOfMeasure {
	OB_UOM_PIXEL = 0,
	OB_UOM_CM = 1,
	OB_UOM_INCH = 2
} OB_UNIT_OF_MEASURE;

typedef enum OBBarcodeType {
	OB_CODABAR = 0,
	OB_CODE11 = 1,
	OB_CODE2OF5 = 2,
	OB_INTERLEAVED25 = 3,
	OB_CODE39 = 4,
	OB_CODE128 = 7,
	OB_CODE128A = 8,
	OB_CODE128B = 9,
	OB_CODE128C = 10,
	OB_EAN128 = 11,
	OB_EAN8 = 12,
	OB_EAN8_2 = 13,
	OB_EAN8_5 = 14,
	OB_EAN13 = 15,
	OB_EAN13_2 = 16,
	OB_EAN13_5 = 17,
	OB_ISBN = 18,
	OB_ISBN_2 = 19,
	OB_ISBN_5 = 20,
	OB_ISSN = 21,
	OB_ISSN_2 = 22,
	OB_ISSN_5 = 23,
	OB_ITF14 = 24,
	OB_UPCA = 36,
	OB_UPCA_2 = 37,
	OB_UPCA_5 = 38,
	OB_UPCE = 39,
	OB_UPCE_2 = 40,
	OB_UPCE_5 = 41
	//	More ...
} OB_BARCODE_TYPE;

typedef enum OBCodabarStartStopChar {
	OB_CODABAR_A = 0,
	OB_CODABAR_B = 1,
	OB_CODABAR_C = 2,
	OB_CODABAR_D = 3
} OB_CODABAR_START_STOP_CHAR;

typedef enum OBRotate {
	OB_Rotate0 = 0,
	OB_Rotate90 = 1,
	OB_Rotate180 = 2,
	OB_Rotate270 = 3
} OB_ROTATE;

typedef enum OBFNC1 {
	OB_FNC1_NONE = 0,
	OB_FNC1_1ST_POS = 1,
	OB_FNC1_2ND_POS = 2
} OB_FNC1;

typedef enum OBDataMatrixFormatMode {
	OB_DATAMATRIX_Format_10X10 = 0,
	OB_DATAMATRIX_Format_12X12 = 1,
	OB_DATAMATRIX_Format_14X14 = 2,
	OB_DATAMATRIX_Format_16X16 = 3,
	OB_DATAMATRIX_Format_18X18 = 4,
	OB_DATAMATRIX_Format_20X20 = 5,
	OB_DATAMATRIX_Format_22X22 = 6,
	OB_DATAMATRIX_Format_24X24 = 7,
	OB_DATAMATRIX_Format_26X26 = 8,
	OB_DATAMATRIX_Format_32X32 = 9,
	OB_DATAMATRIX_Format_36X36 = 10,
	OB_DATAMATRIX_Format_40X40 = 11,
	OB_DATAMATRIX_Format_44X44 = 12,
	OB_DATAMATRIX_Format_48X48 = 13,
	OB_DATAMATRIX_Format_52X52 = 14,
	OB_DATAMATRIX_Format_64X64 = 15,
	OB_DATAMATRIX_Format_72X72 = 16,
	OB_DATAMATRIX_Format_80X80 = 17,
	OB_DATAMATRIX_Format_88X88 = 18,
	OB_DATAMATRIX_Format_96X96 = 19,
	OB_DATAMATRIX_Format_104X104 = 20,
	OB_DATAMATRIX_Format_120X120 = 21,
	OB_DATAMATRIX_Format_132X132 = 22,
	OB_DATAMATRIX_Format_144X144 = 23,
	OB_DATAMATRIX_Format_8X18 = 24,
	OB_DATAMATRIX_Format_8X32 = 25,
	OB_DATAMATRIX_Format_12X26 = 26,
	OB_DATAMATRIX_Format_12X36 = 27,
	OB_DATAMATRIX_Format_16X36 = 28,
	OB_DATAMATRIX_Format_16X48 = 29
} OB_DATAMATRIX_FORMAT_MODE;

typedef enum OBDataMatrixDataMode {
	OB_DATAMATRIX_Auto = 0,
	OB_DATAMATRIX_ASCII = 1,
	OB_DATAMATRIX_C40 = 2,
	OB_DATAMATRIX_Text = 3,
	OB_DATAMATRIX_X12 = 4,
	OB_DATAMATRIX_Edifact = 5,
	OB_DATAMATRIX_Base256 = 6,
	OB_DATAMATRIX_Customer = 7    //  User should provide all mode shifting information in message
} OB_DATAMATRIX_DATA_MODE;

typedef enum OBPDF417DataMode {
	OB_PDF417_Auto = 0,              //  Support all three modes together
	OB_PDF417_Text = 1,
	OB_PDF417_Byte = 2,
	OB_PDF417_Numeric = 3,
	OB_PDF417_Customer = 4     //  User should provide all mode shifting information in message
} OB_PDF417_DATA_MODE;

typedef enum OBPDF417ECL {
	OB_PDF417_Level_0 = 0,
	OB_PDF417_Level_1 = 1,
	OB_PDF417_Level_2 = 2,
	OB_PDF417_Level_3 = 3,
	OB_PDF417_Level_4 = 4,
	OB_PDF417_Level_5 = 5,
	OB_PDF417_Level_6 = 6,
	OB_PDF417_Level_7 = 7,
	OB_PDF417_Level_8 = 8
} OB_PDF417_ECL;

typedef enum OBQRCodeDataMode {
	OB_QRCODE_Auto = 0,
	OB_QRCODE_AlphaNumeric = 1,
	OB_QRCODE_Byte = 2,
	OB_QRCODE_Numeric = 3,
	OB_QRCODE_Kanji = 4,
	OB_QRCODE_Customer = 5
} OB_QRCODE_DATA_MODE;

typedef enum OBQRCodeECL {
	OB_QRCODE_L = 0,
	OB_QRCODE_M = 1,
	OB_QRCODE_Q = 2,
	OB_QRCODE_H = 3
} OB_QRCODE_ECL;

typedef enum OBQRCodeVersion {
	OB_QRCODE_V1 = 1,
	OB_QRCODE_V2 = 2,
	OB_QRCODE_V3 = 3,
	OB_QRCODE_V4 = 4,
	OB_QRCODE_V5 = 5,
	OB_QRCODE_V6 = 6,
	OB_QRCODE_V7 = 7,
	OB_QRCODE_V8 = 8,
	OB_QRCODE_V9 = 9,
	OB_QRCODE_V10 = 10,
	OB_QRCODE_V11 = 11,
	OB_QRCODE_V12 = 12,
	OB_QRCODE_V13 = 13,
	OB_QRCODE_V14 = 14,
	OB_QRCODE_V15 = 15,
	OB_QRCODE_V16 = 16,
	OB_QRCODE_V17 = 17,
	OB_QRCODE_V18 = 18,
	OB_QRCODE_V19 = 19,
	OB_QRCODE_V20 = 20,
	OB_QRCODE_V21 = 21,
	OB_QRCODE_V22 = 22,
	OB_QRCODE_V23 = 23,
	OB_QRCODE_V24 = 24,
	OB_QRCODE_V25 = 25,
	OB_QRCODE_V26 = 26,
	OB_QRCODE_V27 = 27,
	OB_QRCODE_V28 = 28,
	OB_QRCODE_V29 = 29,
	OB_QRCODE_V30 = 30,
	OB_QRCODE_V31 = 31,
	OB_QRCODE_V32 = 32,
	OB_QRCODE_V33 = 33,
	OB_QRCODE_V34 = 34,
	OB_QRCODE_V35 = 35,
	OB_QRCODE_V36 = 36,
	OB_QRCODE_V37 = 37,
	OB_QRCODE_V38 = 38,
	OB_QRCODE_V39 = 39,
	OB_QRCODE_V40 = 40
} OB_QRCODE_VERSION;


//static OB_BARCODE_TYPE LINEAR_DEFAULT_TYPE = OB_CODE39;
#define LINEAR_DEFAULT_TYPE		((OB_BARCODE_TYPE)7)
//static NSString *LINEAR_DEFAULT_DATA = @"12345";
#define	LINEAR_DEFAULT_DATA		(@"123456");
#define LINEAR_DEFAULT_ADDCHECKSUM		(TRUE)

//static OB_UNIT_OF_MEASURE LINEAR_DEFAULT_UOM = OB_UOM_PIXEL;
#define LINEAR_DEFAULT_UOM	((OB_UNIT_OF_MEASURE)0)
#define LINEAR_DEFAULT_X	(1.0f)
#define LINEAR_DEFAULT_Y	(60.0f)
#define LINEAR_DEFAULT_LEFT_MARGIN		(0.0f)
#define LINEAR_DEFAULT_RIGHT_MARGIN		(0.0f)
#define LINEAR_DEFAULT_TOP_MARGIN		(0.0f)
#define LINEAR_DEFAULT_BOTTOM_MARGIN	(0.0f)
#define LINEAR_DEFAULT_RESOLUTION		72
//static OB_ROTATE LINEAR_DEFAULT_ROTATE = OB_Rotate0;
#define LINEAR_DEFAULT_ROTATE	((OB_ROTATE)0)
#define LINEAR_DEFAULT_BARCODE_WIDTH	(0.0f)
#define LINEAR_DEFAULT_BARCODE_HEIGHT	(0.0f)

#define LINEAR_DEFAULT_SHOW_TEXT			(TRUE)
#define LINEAR_DEFAULT_SHOW_CHECKSUM_CHAR	(TRUE)
//static NSFont *LINEAR_DEFAULT_TEXT_FONT = ([[NSFont alloc] fontWithName: (@"Arial") size: (9)]);
#define LINEAR_DEFAULT_TEXT_MARGIN		(6.0f)

//static NSString *LINEAR_DEFAULT_SUP_DATA = @"";
#define LINEAR_DEFAULT_SUP_DATA			(@"")
#define LINEAR_DEFAULT_SUP_HEIGHT		(0.8f)
#define LINEAR_DEFAULT_SUP_SPACE		(15.0f)

#define	LINEAR_DEFAULT_I		1.0f
#define LINEAR_DEFAULT_N		2.0f
#define LINEAR_DEFAULT_ShOW_START_STOP_IN_TEXT	(TRUE)

#define	LINEAR_DEFAULT_BEARER_BAR_HORI	(1.0f)
#define	LINEAR_DEFAULT_BEARER_BAR_VERT	(1.0f)

#define LINEAR_DEFAULT_PROCESS_TILDE			(FALSE)
#define LINEAR_DEFAULT_APPLICATION_INDICATOR	0

//static OB_CODABAR_START_STOP_CHAR LINEAR_DEFAULT_CODABAR_START_CHAR = OB_CODABAR_A;
#define LINEAR_DEFAULT_CODABAR_START_CHAR	((OB_CODABAR_START_STOP_CHAR)0)
//static OB_CODABAR_START_STOP_CHAR LINEAR_DEFAULT_CODABAR_STOP_CHAR = OB_CODABAR_A;
#define LINEAR_DEFAULT_CODABAR_STOP_CHAR	((OB_CODABAR_START_STOP_CHAR)0)

//	DataMatrix Default
//static NSString *DATAMATRIX_DEFAULT_DATA = @"DataMatrix";
#define	DATAMATRIX_DEFAULT_DATA				(@"DataMatrix")
#define DATAMATRIX_DEFAULT_PROCESS_TILDE	(TRUE)

//static OB_DATAMATRIX_DATA_MODE DATAMATRIX_DEFAULT_DATA_MODE = OB_DATAMATRIX_ASCII;
#define DATAMATRIX_DEFAULT_DATA_MODE		((OB_DATAMATRIX_DATA_MODE)1)
//static OB_DATAMATRIX_FORMAT_MODE DATAMATRIX_DEFAULT_FORMAT_MODE = OB_DATAMATRIX_Format_10X10;
#define	DATAMATRIX_DEFAULT_FORMAT_MODE		((OB_DATAMATRIX_FORMAT_MODE)0)

//static OB_FNC1 DATAMATRIX_DEFAULT_FNC1 = OB_FNC1_NONE;
#define DATAMATRIX_DEFAULT_FNC1			((OB_FNC1)0)
#define DATAMATRIX_DEFAULT_APPLICATION_INDICATOR	0
#define DATAMATRIX_DEFAULT_STRUCTURE_APPEND		(FALSE)
#define DATAMATRIX_DEFAULT_SYMBOL_COUNT		0
#define DATAMATRIX_DEFAULT_SYMBOL_INDEX		0
#define DATAMATRIX_DEFAULT_FILE_ID			0

//static ImageFormat DefaultImageFormat = ImageFormat.Png;

//static OB_UNIT_OF_MEASURE DATAMATRIX_DEFAULT_UOM = OB_UOM_PIXEL;
#define DATAMATRIX_DEFAULT_UOM	((OB_UNIT_OF_MEASURE)0)
#define DATAMATRIX_DEFAULT_X		3
#define DATAMATRIX_DEFAULT_LEFT_MARGIN		0
#define DATAMATRIX_DEFAULT_RIGHT_MARGIN		0
#define DATAMATRIX_DEFAULT_TOP_MARGIN		0
#define DATAMATRIX_DEFAULT_BOTTOM_MARGIN	0
#define DATAMATRIX_DEFAULT_RESOLUTION		72
//static OB_ROTATE DATAMATRIX_DEFAULT_ROTATE = OB_Rotate0;
#define DATAMATRIX_DEFAULT_ROTATE	((OB_ROTATE)0)
#define DATAMATRIX_DEFAULT_BARCODE_WIDTH	0
#define DATAMATRIX_DEFAULT_BARCODE_HEIGHT	0

//	QRCode Default
//static NSString *QRCODE_DEFAULT_DATA = @"QRCode";
#define QRCODE_DEFAULT_DATA				(@"QRCode")
#define QRCODE_DEFAULT_PROCESS_TILDE	(TRUE)
//static OB_QRCODE_DATA_MODE QRCODE_DEFAULT_DATA_MODE = OB_QRCODE_Auto;
#define QRCODE_DEFAULT_DATA_MODE	((OB_QRCODE_DATA_MODE)0)
//static OB_QRCODE_ECL QRCODE_DEFAULT_ECL = OB_QRCODE_L;
#define QRCODE_DEFAULT_ECL		((OB_QRCODE_ECL)0)
#define QRCODE_DEFAULT_ECI		3
//static OB_FNC1 QRCODE_DEFAULT_FNC1 = OB_FNC1_NONE;
#define QRCODE_DEFAULT_FNC1			((OB_FNC1)0)
#define QRCODE_DEFAULT_APPLICATION_INDICATOR	0
#define QRCODE_DEFAULT_STRUCTURE_APPEND		(FALSE)
#define QRCODE_DEFAULT_SYMBOL_COUNT		0
#define QRCODE_DEFAULT_SYMBOL_INDEX		0
#define QRCODE_DEFAULT_PARITY			0
//static OB_QRCODE_VERSION QRCODE_DEFAULT_VERSION = OB_QRCODE_V1;
#define QRCODE_DEFAULT_VERSION		((OB_QRCODE_VERSION)1)

//static ImageFormat DefaultImageFormat = ImageFormat.Png;

//static OB_UNIT_OF_MEASURE QRCODE_DEFAULT_UOM = OB_UOM_PIXEL;
#define QRCODE_DEFAULT_UOM	((OB_UNIT_OF_MEASURE)0)
#define QRCODE_DEFAULT_X	2
#define QRCODE_DEFAULT_LEFT_MARGIN		0
#define QRCODE_DEFAULT_RIGHT_MARGIN		0
#define QRCODE_DEFAULT_TOP_MARGIN		0
#define QRCODE_DEFAULT_BOTTOM_MARGIN	0
#define QRCODE_DEFAULT_RESOLUTION		72
//static OB_ROTATE QRCODE_DEFAULT_ROTATE = OB_Rotate0;
#define QRCODE_DEFAULT_ROTATE	((OB_ROTATE)0)
#define QRCODE_DEFAULT_BARCODE_WIDTH	0
#define QRCODE_DEFAULT_BARCODE_HEIGHT	0





